name: CI workflow

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install
        uses: npm ci
      - name: Tests
        uses: npm run test
